pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'docker-hub-credentials'
        DOCKER_IMAGE = 'hannah213/finead-todo-app'
    }

    stages {

        stage('Install Dependencies') {
            steps {
                dir('TODO') {
                    sh 'npm install'
                }
            }
        }

        stage('Build Application') {
            steps {
                dir('TODO') {
                    sh 'npm run build || true'
                }
            }
        }

        stage('Containerize Application') {
            steps {
                dir('TODO') {
                    script {
                        docker.build("${DOCKER_IMAGE}:latest")
                    }
                }
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: DOCKERHUB_CREDENTIALS,
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {

                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    docker push ${DOCKER_IMAGE}:latest
                    '''
                }
            }
        }

    }
}